// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejvtdxngsrrrqaihtgih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdnRkeG5nc3JycnFhaWh0Z2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODQ4NDIsImV4cCI6MjA2MDA2MDg0Mn0.IYVWCnW6g5xqvNcaMYhR51w9AdII2fKpyGe3ag-HQvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);